export const greetings = [
  "hi",
  "hello",
  "hey",
  "yo",
  "heyy",
  "hii",
  "helloo",
  "hey there",
  "hi there",
  "good morning",
  "gm",
  "good night",
  "gn",
  "good afternoon",
  "good evening",
  "namaste",
  "namste",
  "namaskar",
  "salaam",
  "adab",
  "ram ram",
  "radhe radhe",
  "jai shree ram",
  "hare krishna",
  "kem cho",
  "kaise ho",
  "kya haal hai",
  "kya scene hai",
  "bhai kya haal",
  "oye",
  "yo yo",
  "wassup",
  "sup",
  "how r u",
  "how are you",
  "howdy",
];

export const declineWords = [
  "no",
  "nah",
  "nahi",
  "not",
  "cancel",
  "stop",
  "never",
  "nope",
  "don't",
  "do not",
  "refuse",
  "decline",
  "pass",
  "skip",
  "exit",
  "leave",
  "abort",
  "quit",
  "go back",
  "back",
  "nothing",
  "negative",
  "no way",
  "i don't want",
  "mujhe nahi chahiye",
  "chod do",
  "band karo",
  "mat karo",
  "leave it",
  "ignore",
];

export const greetingReplies = [
  (name) => `Hello ${name || "there"}! How can I assist you today?`,
  (name) => `Hey ${name || "friend"}! What can I help you with?`,
  (name) => `Hi ${name || "there"}! Need any assistance?`,
  (name) => `Hey there ${name || ""}, how may I help you today?`,
  (name) => `Hi ${name || "there"} 👋 What brings you here today?`,
  (name) => `Welcome ${name || "buddy"}! Let me know how I can help.`,
  (name) => `Good to see you ${name || ""}! What can I do for you?`,
  (name) => `Hey ${name || ""}! I’m here to help. What’s up?`,
  (name) => `Hi ${name || ""}, hope you’re doing great! How can I help?`,
  (name) => `Yo ${name || "there"}! Need something? I’m all ears.`,
];
